version: "3.7"

services:
  holamundo:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./
        target: "/usr/node/app"
